apiVersion: v2
name: monolithic-ran
type: application
icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png
version: 2.2
description: Charts for testing monolithic ran use case

appVersion: 2.2

keywords:
  - 5GCN
  - AMF
  - SMF
  - NRF
  - UPF
  - UDM
  - UDR
  - AUSF
  - gNB
  - NRUE
#  - Traffic_server

maintainers:
  - name:  OPENAIRINTERFACE
    email: contact@openairinterface.org

dependencies:
- condition: mysql.enabled
  name: mysql
  repository: "file://../../oai-5g-core/mysql"
  version: 9.0.1
- condition: oai-nrf.enabled
  name: oai-nrf
  repository: "file://../../oai-5g-core/oai-nrf"
  version: v2.2.0
  appVersion: develop
- condition: oai-udr.enabled
  name: oai-udr
  repository: "file://../../oai-5g-core/oai-udr"
  version: v2.2.0
  appVersion: develop
- condition: oai-udm.enabled
  name: oai-udm
  repository: "file://../../oai-5g-core/oai-udm"
  version: v2.2.0
  appVersion: develop
- condition: oai-ausf.enabled
  name: oai-ausf
  repository: "file://../../oai-5g-core/oai-ausf"
  version: v2.2.0
  appVersion: develop
- condition: oai-amf.enabled
  name: oai-amf
  repository: "file://../../oai-5g-core/oai-amf"
  version: v2.2.0
  appVersion: develop
- condition: oai-smf.enabled
  name: oai-smf
  repository: "file://../../oai-5g-core/oai-smf"
  version: v2.2.0
  appVersion: develop
- condition: oai-upf.enabled
  name: oai-upf
  repository: "file://../../oai-5g-core/oai-upf"
  version: v2.2.0
  appVersion: develop
- condition: oai-gnb.enabled
  name: oai-gnb
  repository: "file://../../oai-5g-ran/oai-gnb"
  version: 2.4.0
  appVersion: develop
- condition: oai-nr-ue.enabled
  name: oai-nr-ue
  repository: "file://../../oai-5g-ran/oai-nr-ue"
  version: 2.4.0
  appVersion: develop
- condition: oai-traffic-server.enabled
  name: oai-traffic-server
  repository: "file://../../oai-5g-core/oai-traffic-server"
  version: v2.2.0
  appVersion: v2.2.0
