apiVersion: v2
name: oai-5g-advance
version: v2.2.0.0
appVersion: v2.2.0
icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png
description: OAI 5G Release 16 Core Network
type: application

keywords:
  - 5GCN
  - SLICING
  - AMF
  - SMF
  - NRF
  - UDM
  - UDR
  - NSSF
  - AUSF
  - UPF
  - LMF
  # - PCF
  - Traffic_server

maintainers:
  - name:  OPENAIRINTERFACE
    email: contact@openairinterface.org

dependencies:
- condition: mysql.enabled
  name: mysql
  repository: "file://../mysql"
  version: 9.0.1
- condition: oai-nssf.enabled
  name: oai-nssf
  repository: "file://../oai-nssf"
  version: v2.2.0
  appVersion: develop
- condition: oai-nrf.enabled
  name: oai-nrf
  repository: "file://../oai-nrf"
  version: v2.2.0
  appVersion: develop
- condition: oai-udr.enabled
  name: oai-udr
  repository: "file://../oai-udr"
  version: v2.2.0
  appVersion: develop
- condition: oai-udm.enabled
  name: oai-udm
  repository: "file://../oai-udm"
  version: v2.2.0
  appVersion: develop
- condition: oai-ausf.enabled
  name: oai-ausf
  repository: "file://../oai-ausf"
  version: v2.2.0
  appVersion: develop
- condition: oai-amf.enabled
  name: oai-amf
  repository: "file://../oai-amf"
  version: v2.2.0
  appVersion: develop
- condition: oai-smf.enabled
  name: oai-smf
  repository: "file://../oai-smf"
  version: v2.2.0
  appVersion: develop
- condition: oai-upf.enabled
  name: oai-upf
  repository: "file://../oai-upf"
  version: v2.2.0
  appVersion: develop
- condition: oai-lmf.enabled
  name: oai-lmf
  repository: "file://../oai-lmf"
  version: v2.2.0
  appVersion: develop
# - condition: oai-pcf.enabled
#   name: oai-pcf
#   repository: "file://../oai-pcf"
#   version: v2.2.0
#   appVersion: develop
- condition: oai-traffic-server.enabled
  name: oai-traffic-server
  repository: "file://../oai-traffic-server"
  version: v2.2.0
  appVersion: v2.2.0
