Active_gNBs: ["gNB-OAI"]
Asn1_verbosity: "none"

gNBs:
  - gNB_ID: 0xe00
    gNB_name: "gNB-OAI"
    tracking_area_code: 1
    plmn_list:
      - mcc: 208
        mnc: 99
        mnc_length: 2
        snssaiList:
          - sst: 1
    nr_cellid: 1

    pdsch_AntennaPorts_XP: 2
    pdsch_AntennaPorts_N1: 2
    maxMIMO_layers: 2
    pusch_AntennaPorts: 4
    do_CSIRS: 1
    do_SRS: 0
    sib1_tda: 15

    servingCellConfigCommon:
      - physCellId: 0
        absoluteFrequencySSB: 623328
        dl_frequencyBand: 78
        dl_absoluteFrequencyPointA: 620058
        dl_offstToCarrier: 0
        dl_subcarrierSpacing: 1
        dl_carrierBandwidth: 273
        initialDLBWPlocationAndBandwidth: 1099
        initialDLBWPsubcarrierSpacing: 1
        initialDLBWPcontrolResourceSetZero: 11
        initialDLBWPsearchSpaceZero: 0

        ul_frequencyBand: 78
        ul_offstToCarrier: 0
        ul_subcarrierSpacing: 1
        ul_carrierBandwidth: 273
        pMax: 23
        initialULBWPlocationAndBandwidth: 1099
        initialULBWPsubcarrierSpacing: 1

        prach_ConfigurationIndex: 152
        prach_msg1_FDM: 0
        prach_msg1_FrequencyStart: 0
        zeroCorrelationZoneConfig: 0
        preambleReceivedTargetPower: -100
        preambleTransMax: 8
        powerRampingStep: 3
        ssb_perRACH_OccasionAndCB_PreamblesPerSSB_PR: 4
        ssb_perRACH_OccasionAndCB_PreamblesPerSSB: 15
        ra_ContentionResolutionTimer: 7
        rsrp_ThresholdSSB: 19
        prach_RootSequenceIndex_PR: 2
        prach_RootSequenceIndex: 1
        msg1_SubcarrierSpacing: 1
        restrictedSetConfig: 0
        msg3_DeltaPreamble: 2
        p0_NominalWithGrant: -96
        pucchGroupHopping: 0
        hoppingId: 0
        p0_nominal: -96
        ssb_PositionsInBurst_Bitmap: 0x1
        ssb_periodicityServingCell: 2
        dmrs_TypeA_Position: 0
        subcarrierSpacing: 1
        referenceSubcarrierSpacing: 1
        dl_UL_TransmissionPeriodicity: 5
        nrofDownlinkSlots: 3
        nrofDownlinkSymbols: 6
        nrofUplinkSlots: 1
        nrofUplinkSymbols: 4
        ssPBCH_BlockPower: -10

    SCTP:
      SCTP_INSTREAMS: 2
      SCTP_OUTSTREAMS: 2

    amf_ip_address:
      - ipv4: "172.21.6.5"

    NETWORK_INTERFACES:
      GNB_IPV4_ADDRESS_FOR_NG_AMF: "172.21.16.51"
      GNB_IPV4_ADDRESS_FOR_NGU: "172.21.16.51"
      GNB_PORT_FOR_S1U: 2152

MACRLCs:
  - num_cc: 1
    tr_s_preference: "local_L1"
    tr_n_preference: "local_RRC"
    pusch_TargetSNRx10: 180
    pucch_TargetSNRx10: 220
    dl_bler_target_upper: 0.35
    dl_bler_target_lower: 0.15
    ul_bler_target_upper: 0.35
    ul_bler_target_lower: 0.15
    pusch_FailureThres: 1000
    ul_max_mcs: 28

L1s:
  - num_cc: 1
    tr_n_preference: "local_mac"
    prach_dtx_threshold: 100
    pucch0_dtx_threshold: 80
    pusch_dtx_threshold: 10
    max_ldpc_iterations: 15
    tx_amp_backoff_dB: 15
    L1_rx_thread_core: 8
    L1_tx_thread_core: 10
    phase_compensation: 0

RUs:
  - local_rf: "no"
    nb_tx: 4
    nb_rx: 4
    att_tx: 0
    att_rx: 0
    bands: [78]
    max_pdschReferenceSignalPower: -27
    max_rxgain: 75
    sf_extension: 0
    eNB_instances: [0]
    ru_thread_core: 9
    sl_ahead: 10
    tr_preference: "raw_if4p5"
    do_precoding: 0

security:
  ciphering_algorithms: ["nea0"]
  integrity_algorithms: ["nia2", "nia0"]
  drb_ciphering: "yes"
  drb_integrity: "no"

log_config:
  global_log_level: "info"
  hw_log_level: "info"
  phy_log_level: "info"
  mac_log_level: "info"
  rlc_log_level: "info"
  pdcp_log_level: "info"
  rrc_log_level: "info"
  ngap_log_level: "info"
  f1ap_log_level: "info"

fhi_72:
  dpdk_devices: ["0000:c1:11.0", "0000:c1:11.1"]
  system_core: 0
  io_core: 1
  dpdk_mem_size: 0
  dpdk_iova_mode: "VA"
  worker_cores: [2]
  ru_addr: ["70:b3:d5:e1:5b:81", "70:b3:d5:e1:5b:81"]
  mtu: 9600
  fh_config:
    - T1a_cp_dl: [419, 470]
      T1a_cp_ul: [285, 336]
      T1a_up: [294, 345]
      Ta4: [0, 200]
      ru_config:
        iq_width: 9
        iq_width_prach: 9
thread-pool: "20,21,22,23,24,25,26,27,28"
