apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}
    {{- include "ims.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ims.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- include "ims.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - name: ims
        image: oaisoftwarealliance/ims:latest
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        volumeMounts:
        - mountPath: /etc/asterisk/sip.conf
          name: sip
          subPath: sip.conf
        - mountPath: /etc/asterisk/users.conf
          name: users
          subPath: users.conf
        ports:
        - containerPort: 5060
          name: ims
      volumes:
        - name: sip
          configMap:
            name: ims-sip
        - name: users
          configMap:
            name: ims-users
        - name: startup
          configMap:
            name: ims-cm
            defaultMode: 0777
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: {{ .Chart.Name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
