Active_gNBs:
  - "oai-gnb"

# Asn1_verbosity, choice in: none, info, annoying
Asn1_verbosity: "none"
Num_Threads_PUSCH: 8
sa: 1

gNBs:
  - gNB_ID: 0xe00
    # cell_type: "CELL_MACRO_GNB"
    gNB_name: "oai-gnb"

    # Tracking area code, 0x0000 and 0xfffe are reserved values
    tracking_area_code: 1

    plmn_list:
      - mcc: 208
        mnc: 99
        mnc_length: 2
        snssaiList:
          - sst: 1

    nr_cellid: 12345678
    tr_s_preference: "f1"

    local_s_address: "127.0.0.1"
    remote_s_address: "127.0.0.1"
    local_s_portc: 501
    local_s_portd: 2153
    remote_s_portc: 500
    remote_s_portd: 2153

    # ------- SCTP definitions
    SCTP:
      SCTP_INSTREAMS: 2
      SCTP_OUTSTREAMS: 2

    # -------- AMF parameters
    amf_ip_address:
      - ipv4: "127.0.0.1"

    E1_INTERFACE:
      - type: "cp"
        ipv4_cucp: "127.0.0.1"
        port_cucp: 38462
        ipv4_cuup: "0.0.0.0"
        port_cuup: 38462

    NETWORK_INTERFACES:
      GNB_IPV4_ADDRESS_FOR_NG_AMF: "127.0.0.1"

security:
  # preferred ciphering algorithms
  ciphering_algorithms:
    - "nea0"

  # preferred integrity algorithms
  integrity_algorithms:
    - "nia2"
    - "nia0"

  # setting 'drb_ciphering' to "no" disables ciphering for DRBs
  drb_ciphering: "yes"
  drb_integrity: "no"

log_config:
  global_log_level: "info"
  hw_log_level: "info"
  phy_log_level: "info"
  mac_log_level: "info"
  rlc_log_level: "debug"
  pdcp_log_level: "info"
  rrc_log_level: "info"
  f1ap_log_level: "info"
  ngap_log_level: "debug"
